"""initial schema

Revision ID: 7b3040442bd7
Revises: 
Create Date: 2026-09-28 10:48:33.019691

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b3040442bd7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hazards',
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('influence_radius_m', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('UNCONFIRMED', 'CONFIRMED', 'MODERATION', 'ARCHIVED', name='hazard_status'), nullable=False),
    sa.Column('first_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmations_count', sa.Integer(), nullable=False),
    sa.Column('refutations_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('AGENT', 'MODERATOR', name='hazard_source'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hazards_type'), 'hazards', ['type'], unique=False)
    op.create_table('users',
    sa.Column('role', sa.Enum('BLIND_USER', 'VOLUNTEER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('firmware_version', sa.String(length=32), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_token_hash'), 'devices', ['token_hash'], unique=True)
    op.create_table('dialog_turns',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'AGENT', name='dialog_role'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_compressed', sa.Boolean(), nullable=False),
    sa.Column('summary_of_turn_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['summary_of_turn_id'], ['dialog_turns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_memories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('languages', sa.ARRAY(sa.String(length=8)), nullable=False),
    sa.Column('districts', sa.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('skills', sa.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('availability_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_status', sa.Enum('ONLINE', 'OFFLINE', 'BUSY', name='volunteer_status'), nullable=False),
    sa.Column('response_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('assistance_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('agent_summary', sa.String(), nullable=True),
    sa.Column('assigned_volunteer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'ROUTED', 'ACCEPTED', 'IN_SESSION', 'CLOSED', 'ESCALATED', name='assistance_status'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_volunteer_id'], ['volunteers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('client_event_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('VOICE_REPORT', 'AUTO_DETECTION', 'ASSISTANCE', name='event_kind'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('detections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('media', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.Column('battery', sa.Integer(), nullable=True),
    sa.Column('offline_queued', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSED', 'ERROR', name='event_processing_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'client_event_id', name='uq_device_client_event')
    )
    op.create_table('hazard_events',
    sa.Column('hazard_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('relation', sa.Enum('CONFIRMS', 'REFUTES', name='hazard_event_relation'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['hazard_id'], ['hazards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshots_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['assistance_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('hazard_events')
    op.drop_table('events')
    op.drop_table('assistance_requests')
    op.drop_table('volunteers')
    op.drop_table('user_memories')
    op.drop_table('dialog_turns')
    op.drop_index(op.f('ix_devices_token_hash'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('users')
    op.drop_index(op.f('ix_hazards_type'), table_name='hazards')
    op.drop_table('hazards')
    # ### end Alembic commands ###
